series: yaml-income-test
artifact_storage_uri: /Users/ssc/projects/arguseyes/mlruns/

pipeline:
  template: classification
  path: /Users/ssc/projects/arguseyes/arguseyes/example_pipelines/income-classifier.py
  working_directory: /Users/ssc/projects/arguseyes/arguseyes/example_pipelines/
  detect_issues:
  data-refinements:
    - refinement:
        name: fairness_metrics
        params:
          sensitive_attribute: sex
          non_protected_class: Male
    - refinement:
        name: fairness_metrics
        params:
          sensitive_attribute: race
          non_protected_class: White