series: development
artifact_storage_uri: /Users/ssc/projects/arguseyes/mlruns/

pipeline:
  path: /Users/ssc/projects/arguseyes/arguseyes/example_pipelines/mlflow-regression-nyctaxifare.py
  template: classification
  detect_issues:
     - data_leakage
