series: development
artifact_storage_uri: /Users/ssc/projects/arguseyes/mlruns/

pipeline:
  template: classification
  path: /Users/ssc/projects/arguseyes/arguseyes/example_pipelines/mlinspect-computervision-sneakers.py
  working_directory: /Users/ssc/projects/arguseyes/arguseyes/example_pipelines/
  detect_issues:
  data-refinements:
    - refinement:
        name: data_valuation
        params:
          k: 10
          num_test_samples: 100