series: development
artifact_storage_uri: /Users/ssc/projects/arguseyes/mlruns/

pipeline:
  template: classification
  path: /Users/ssc/projects/arguseyes/arguseyes/example_pipelines/openml-classification-incomelevel.py
  detect_issues:
    - issue:
        name: fairness
        params:
          sensitive_attribute: sex
          privileged_class: Male
          metric: equal_opportunity
          max_difference: 0.01
    - issue:
        name: fairness
        params:
          sensitive_attribute: race
          privileged_class: White
          metric: statistical_parity
          max_difference: 0.02