series: time-management-decision-tree
artifact_storage_uri: ../mlruns/

pipeline:
  template: classification
  path: time-management__decisiontree.py
  working_directory: .
  detect_issues:
    - constant_features
    - label_shift
    - traintest_overlap
  data-refinements:
    - refinement:
        name: input_usage
    - refinement:
        name: fairness_metrics
        params:
          sensitive_attribute: Nationality
          non_protected_class: China
    - refinement:
        name: fairness_metrics
        params:
          sensitive_attribute: Gender
          non_protected_class: M
